included:
  - Taxi ai

excluded:
  - .build
  - DerivedData

line_length:
  warning: 140
  error: 200
  ignores_comments: true
  ignores_urls: true

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

disabled_rules:
  - trailing_comma
  - todo
  - opening_brace
  - no_space_in_method_call

opt_in_rules:
  - force_unwrapping
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - discouraged_optional_boolean
  - empty_string
  - first_where
  - modifier_order
  - overridden_super_call
  - private_action
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unowned_variable_capture
  - vertical_whitespace_closing_braces

identifier_name:
  min_length:
    warning: 1
  excluded:
    - id
    - x
    - y
    - i
    - to

nesting:
  type_level: 2
  function_level: 3
